### ISSUE TITLE
Doesn't support multiple cursors

### ISSUE THREAD

**Issue by ghost** [wangchunsen/vscode-bracket-select#1]
When trying to select between brackets when multiple cursors are present it only selects at the original cursor location.

**Comment by wangchunsen** [comment]
Duplicate of # Yes, It does not support multiple cursors for now. But this should be a good point to make an enhancement.

**Comment by kanlukasz** [comment]
I also miss this functionality very much.
Is there any chance to add this?

_Sorry for no PR. I'm just a php dev_

**Comment by kanlukasz** [comment]
Was it pushed to the marketplace?
I don't see updates in VSCode
