### ISSUE TITLE
Enhancement: Support multi-cursor

### ISSUE THREAD

**Issue by alfredbirk** [wangchunsen/vscode-bracket-select#10]
Should support selection with multiple cursors

**Comment by kanlukasz** [comment]
It is already implemented:
https://github.com/wangchunsen/vscode-bracket-select/pull/8

**Comment by wangchunsen** [comment]
Released, please check it [here](https://marketplace.visualstudio.com/items?itemName=chunsen.bracket-select&ssr=false#overview)
