### ISSUE TITLE
Select between html tags

### ISSUE THREAD

**Issue by dili021** [wangchunsen/vscode-bracket-select#13]
Hello, I love the extension and thought it would be at a 100% if you'd be able to <html_tag> **select text between tags** </html_tag>

Keep up the good work!

EDIT: 
Nevermind, I found out that Emmet has this functionality. It's called balance outward for anyone interested.

**Comment by kanlukasz** [comment]
Unfortunately this won't work if your file is PHP (not HTML)
But if you want select tags in PHP files you can use https://marketplace.visualstudio.com/items?itemName=letrieu.expand-region

By the way, the Bracket Select add-on had this option before, but there were problems, e.g. - `if (1 < 2) ...`
