### ISSUE TITLE
Colons on adjacent lines affect each other

### ISSUE THREAD

**Issue by shawn-yee** [wangchunsen/vscode-bracket-select#16]
![2021-06-26 17 33 38](https://user-images.githubusercontent.com/66560386/123508936-18dcbf00-d6a5-11eb-8cd1-2de9d9c75b38.gif)

**Comment by FuPeiJiang** [comment]
it's selecting between the 2 `'`, because they come before `{` and `}`
one solution could be to NOT select between 2 `'` if they are on different lines

another solution : use 1 hotkey(keyboard shortcut) for `'` `'` and 1 hotkey for `{` `}`
___
your high contrast theme do be looking cool, want to share it ? :D

**Comment by shawn-yee** [comment]
Monokai GRS: https://marketplace.visualstudio.com/items?itemName=GoliafRS.monokai-grs#review-details

**Comment by shawn-yee** [comment]
@FuPeiJiang 
Monokai GRS: https://marketplace.visualstudio.com/items?itemName=GoliafRS.monokai-grs#review-details

**Comment by shawn-yee** [comment]
My intention is to do this, and it should look like the GIF of this plugin,it is named 'Select Between'.
https://marketplace.visualstudio.com/items?itemName=Shazbot.select-between
Unfortunately, the extension is installed incorrectly and cannot be used
![select_between](https://user-images.githubusercontent.com/66560386/123515694-037a8b80-d6cb-11eb-89ff-7498bba28f5f.gif)

**Comment by FuPeiJiang** [comment]
@shawn-yee thanks for the theme
___
I could try to fix this,
https://marketplace.visualstudio.com/items?itemName=Shazbot.select-between
but I want to code it myself
___
would you mind installing from a .vsix ? from github releases
or you can build the .vsix yourself after cloning the repo

**Comment by FuPeiJiang** [comment]
wait, I'm not getting the high contrast highlighting from this theme: https://marketplace.visualstudio.com/items?itemName=GoliafRS.monokai-grs#review-details

this yellow highlighting 
![image](https://user-images.githubusercontent.com/42662615/123522849-2175cb00-d68e-11eb-881b-9475e20dbdc5.png)
and red highlighting 
![image](https://user-images.githubusercontent.com/42662615/123522857-2aff3300-d68e-11eb-8df9-8f0d57af5164.png)

**Comment by shawn-yee** [comment]
@FuPeiJiang 

1.'Highlight Line'
https://marketplace.visualstudio.com/items?itemName=cliffordfajardo.highlight-line-vscode#review-details

2.My setting.json about colorful bracket:
"editorBracketMatch.border": "#f00c",
"editorBracketMatch.background": "#f00c",
/* 
"bracket-pair-colorizer-2.activeScopeCSS": [
   "backgroundColor : rgba(255,0,0,50%)"
]
*/
"bracket-pair-colorizer-2.colors": [
    "#0f0",
    "#ff0",
    "#00BFFF",
    "orange",
]

**Comment by shawn-yee** [comment]
@FuPeiJiang 
.vsix ,that's fine

**Comment by shawn-yee** [comment]
@FuPeiJiang 
It's really common to see the same quotes on adjacent lines.
Like package.json, snippet.json, setting.json ...

**Comment by FuPeiJiang** [comment]
@shawn-yee, ty, tried the theme but strained my eyes too much, 
thank you for https://marketplace.visualstudio.com/items?itemName=iceliu.highlight-icemode#review-details, this one I'll keep

you can look at the progress I make if you want : https://github.com/FuPeiJiang/vscode-bracket-select
HARDER THAN I THOUGHT

**Comment by FuPeiJiang** [comment]
@shawn-yee 
what's this extension ? `<const a = {`
![image](https://user-images.githubusercontent.com/42662615/123563867-08037a80-d785-11eb-86ef-950d99ed2950.png)
___
ok so this is the progress :
![Code_NVnY6JhOhW](https://user-images.githubusercontent.com/42662615/123563971-819b6880-d785-11eb-8b70-62779860e34e.png)
didn't find `'` in same line, but found `"` in same line, so highlighted between`"`

gonna do multiline now..

**Comment by shawn-yee** [comment]
@FuPeiJiang 
There are two plugins, and you can choose one of them
After comparison, I chose the first one because it is more detailed
Finally, I created a custom emoji arrow ◀︎ ► ▼ ▲

1.https://marketplace.visualstudio.com/items?itemName=finkivscode.labelclosing

2.https://marketplace.visualstudio.com/items?itemName=wraith13.bracket-lens

**Comment by shawn-yee** [comment]
This extension supports the distinction between colons and bracket, but it has problems with multiple selection.

https://marketplace.visualstudio.com/items?itemName=davidbabel.Clever#review-details

**Comment by shawn-yee** [comment]
This problem is indeed not easy to solve, and I would be grateful if it were finally solved

**Comment by FuPeiJiang** [comment]
I would like to learn how to find these extensions. they aren't even popular
how do you find vscode extensions like these ?
___
https://github.com/DavidBabel/clever-vscode : this is actually really good, I don't need multiple selection support, I'm using this now, ty (don't worry, I'll still continue working on that)

I've seen your issue on that repo: https://github.com/DavidBabel/clever-vscode/issues/ 7
I think it's a FEATURE, not a bug. it HAS multi selection support and was trying to find a common ancestor
though I wouldn't want that feature..

it even has support for `>` and `<`, though it could be mistaken for greater-than and less-than signs. we'll see if it ACTUALLY happens. should do more good than harm.

I've seen the README and it uses this (the actual logic)
https://github.com/dbankier/vscode-quick-select

**Comment by FuPeiJiang** [comment]
I think clever-vscode parses the whole document before doing the select, instead of "looking around the selection", or else it can't possibly know where is inside string and where is outside string

`x3: 'y4', x3: 'y4',`
`x3: 'inside'outside'inside',`

I should change my implementation.
which one do you want ? I could try the looking around one, in case you wanted to select `'ouside'`
I don't think there's any harm, yet..

"looking around the selection" is what wangchunsen/vscode-bracket-select does

**Comment by FuPeiJiang** [comment]
@shawn-yee Pre-release, there's stuff left to do : https://github.com/FuPeiJiang/vscode-bracket-select/releases
you can try with multi-selection

**Comment by FuPeiJiang** [comment]
using this : 1.https://marketplace.visualstudio.com/items?itemName=finkivscode.labelclosing

> Finally, I created a custom emoji arrow ◀︎ ► ▼ ▲

◀︎ is not the correct arrow.

this is the closest one I've found : https://www.compart.com/en/unicode/U+25C4
◄, it's the left version of ►

`"labelClosing.seperatorChar": " ◄ ",` (for those who need it) maybe myself in the future

**Comment by shawn-yee** [comment]
@FuPeiJiang 
I often search for code visualization and enhancement tools, so I can find some amazing plugins.
For example, combined with this plugin, you can customize various block-level operations with a shortcut (copy/cut/delete block).
https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command#review-details

**Comment by shawn-yee** [comment]
@FuPeiJiang 
I often search for code visualization and enhancement tools, so I can find some amazing plugins.
For example, combined with this plugin, you can customize various block-level operations with a shortcut (copy/cut/delete block).
So, the exact match is very important to me, because i have other plugins that depend on it.
https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command#review-details

![Uploading 2021-06-29 16.11.25.gif…]()

**Comment by shawn-yee** [comment]
I tried the .vsix version, and it seems to be causing more problems, which should have been caused by the matching strategy.

Nearby matching doesn't solve the problem at all, and I guess it requires changing the entire matching strategy and parsing the entire document.
In the end, I decided to use that plugin-'Clever VSCode'
https://marketplace.visualstudio.com/items?itemName=davidbabel.Clever

Thank you for your help

**Comment by FuPeiJiang** [comment]
@shawn-yee

> parsing the entire document

multicursor-bracket-select for different languages:
https://github.com/FuPeiJiang/my-bracket-select

please try it:
`yarn`
`yarn install` : will generate .vsix and install the extension

the original:
```javascript
const a = {
  x1 : 'y1',
  x2 : 'y2',
  x3 : 'y3',
  x4 : 4,
  x5 : 5,
}
```

___

this one will work I assure you because I've been using it for a long time before posting here

___

weirdly I came here because [finkivscode.labelclosing](https://marketplace.visualstudio.com/items?itemName=finkivscode.labelclosing) is slow/freezes vscode when opening huge .json files, I found that out using command: `Help: Start Extension Bisect`
