### ISSUE TITLE
Enhancement: Option to unselect

### ISSUE THREAD

**Issue by kanlukasz** [wangchunsen/vscode-bracket-select#6]
Often, by accident I select too much range (too much clicking alt+a). 
Is there any option to go back (uncheck)?

**Comment by Santosh-Gupta** [comment]
I would love to have this as well

**Comment by wangchunsen** [comment]
Good suggestion, will consider to implement it in the next release.

**Comment by alfredbirk** [comment]
You can simply use the "Cursor undo" command, which will undo the last selection 
![Undo select](https://user-images.githubusercontent.com/11172530/82578351-8e19be80-9b8c-11ea-8889-1744eb1443bc.gif)

**Comment by kanlukasz** [comment]
Wow, didn't know about this native function 😲 Thanks 🍻

Anyway, from what I can see, the Readme file has been updated and the command `alt + z` will appear to undo selection.
But this version is probably not pushed to the master yet

**Comment by Santosh-Gupta** [comment]
wow, cntrl+U , can't believe I missed that

**Comment by wangchunsen** [comment]
Released in version 2.0.2, please check it [here](https://marketplace.visualstudio.com/items?itemName=chunsen.bracket-select&ssr=false#overview)
